In [ ]:
Q1. Create a Pandas Series that contains the following data: 4, 8, 15, 16, 23, and 42. Then, print the series.
Ans-

import pandas as pd

# create a Pandas Series
data = [4, 8, 15, 16, 23, 42]
series = pd.Series(data)

# print the series
print(series)

Output:

0     4
1     8
2    15
3    16
4    23
5    42
dtype: int64

In this code, we first import the Pandas library using the import pandas as pd statement. Then, we create a list data containing the values 4, 8, 15, 16, 23, and 42. We use the pd.Series() function to create a Pandas Series series from the list data. Finally, we print the series using the print() function.

In [ ]:
Q2. Create a variable of list type containing 10 elements in it, and apply pandas.Series function on the
variable print it.
Ans-

import pandas as pd

# create a list with 10 elements
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# convert the list to a Pandas Series
my_series = pd.Series(my_list)

# print the series
print(my_series)

Output:
    
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In this code, we first create a list my_list containing 10 elements. We then use the pd.Series() function to create a Pandas Series my_series from the list. Finally, we print the series using the print() function.

In [ ]:
Q3. Create a Pandas DataFrame that contains the following data:

Name
Alice
Bob
Claire

Age
25
30
27

Gender
Female
Male
Female

Then, print the DataFrame.

Ans- 

import pandas as pd

# create a dictionary containing the data
data = {'Name': ['Alice', 'Bob', 'Claire'],
        'Age': [25, 30, 27],
        'Gender': ['Female', 'Male', 'Female']}

# create a Pandas DataFrame from the dictionary
df = pd.DataFrame(data)

# print the DataFrame
print(df)

Output:
    
     Name  Age  Gender
0   Alice   25  Female
1     Bob   30    Male
2  Claire   27  Female

In this code, we first create a dictionary data containing the Name, Age, and Gender data. We then use the pd.DataFrame() function to create a Pandas DataFrame df from the dictionary. Finally, we print the DataFrame using the print() function.

In [ ]:
Q4. What is ‘DataFrame’ in pandas and how is it different from pandas.series? Explain with an example.
Ans-  A DataFrame in pandas is a two-dimensional labeled data structure with columns of potentially different types. It is similar to a spreadsheet or a SQL table, where data is organized in rows and columns, and each column can have a different data type. A DataFrame can be thought of as a collection of Series objects, where each Series represents a column of the DataFrame.

A Series in pandas, on the other hand, is a one-dimensional labeled data structure with a homogeneous data type.

Here's an example to illustrate the difference between a DataFrame and a Series:

import pandas as pd

# create a Pandas Series
s = pd.Series([1, 2, 3, 4, 5])

# create a Pandas DataFrame
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [7, 8, 9]})

# print the Series and DataFrame
print(s)
print(df)


Output:
    
0    1
1    2
2    3
3    4
4    5
dtype: int64
   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In this example, we create a Pandas Series s with the values 1, 2, 3, 4, and 5. We also create a Pandas DataFrame df with three columns A, B, and C, and three rows of data. The data in each column of the DataFrame can have a different data type. In contrast, the data in the Series must be of the same data type.

In [ ]:
Q5. What are some common functions you can use to manipulate data in a Pandas DataFrame? Can
you give an example of when you might use one of these functions?
Ans-
1.head() and tail(): Returns the first or last n rows of the DataFrame. This is useful for quickly checking the data and making sure it is in the expected format.

2.describe(): Generates descriptive statistics for numerical columns in the DataFrame, such as count, mean, standard deviation, minimum, maximum, and quartiles. This is useful for understanding the distribution of the data.

3.dropna(): Removes rows or columns with missing values from the DataFrame. This is useful for cleaning the data before analysis.

4.groupby(): Groups the data in the DataFrame by one or more columns and applies an aggregate function, such as sum, mean, count, etc. This is useful for generating summary statistics by groups.

5.merge(): Combines two or more DataFrames into a single DataFrame based on a common column or index. This is useful for combining data from different sources.

     Here are some examples of head() and tail() functions:
    
import pandas as pd

data = {'Name': ['John', 'Jane', 'Jim', 'Joan', 'Jack', 'Jill', 'Jerry', 'Judy', 'Jacob', 'Jenna'],
        'Age': [25, 30, 35, 40, 45, 50, 55, 60, 65, 70],
        'Gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female']}

df = pd.DataFrame(data)

Output of df:
    
    Name  Age  Gender
0   John   25    Male
1   Jane   30  Female
2    Jim   35    Male
3   Joan   40  Female
4   Jack   45    Male
5   Jill   50  Female
6  Jerry   55    Male
7   Judy   60  Female
8  Jacob   65    Male
9  Jenna   70  Female

Example of head() function:

# show the first 3 rows of the DataFrame
print(df.head(3))

Output:
     Name  Age  Gender
0    John   25    Male
1    Jane   30  Female
2    Jim    35    Male

Example of tail() function:

# show the last 5 rows of the DataFrame
print(df.tail())

Output:
    
     Name  Age  Gender
5    Jill   50  Female
6    Jerry  55    Male
7    Judy   60  Female
8    Jacob  65    Male
9    Jenna  70  Female

In [ ]:
Q6. Which of the following is mutable in nature Series, DataFrame, Panel?
Ans-
In a Series, the data can be modified by assigning new values to individual elements using their index. 

Similarly, in a DataFrame, we can modify values in cells, add or remove columns or rows, and perform various manipulations on the data.

In a Panel, the data can be modified by replacing the entire contents of a panel axis, but it is not possible to modify the shape of the panel. However, it is recommended to use the more versatile and efficient MultiIndex DataFrame in place of Panel, since it provides more functionality and flexibility for most use cases.

In [ ]:
Q7. Create a DataFrame using multiple Series. Explain with an example.
Ans-
We can create a DataFrame by using multiple Pandas Series, which can be thought of as the columns of the DataFrame. Each Series can have a different data type, and they should all have the same length.

import pandas as pd

# Create three Series for the columns
name = pd.Series(['Alice', 'Bob', 'Claire'])
age = pd.Series([25, 30, 27])
gender = pd.Series(['Female', 'Male', 'Female'])

# Combine the Series into a DataFrame
df = pd.DataFrame({'Name': name, 'Age': age, 'Gender': gender})

# Print the resulting DataFrame
print(df)

Output:
    
    Name  Age  Gender
0   Alice   25  Female
1     Bob   30    Male
2   Claire  27  Female
    
In this example, we create three separate Series for the Name, Age, and Gender columns of the DataFrame. We then pass these Series as a dictionary to the pd.DataFrame() function, which creates a DataFrame with the specified column names and the corresponding data from each Series. Finally, we print the resulting DataFrame using the print() function.